### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.Users.Commands
  id: MaintenanceChronicle.Application.Contracts.Users.Commands
  children:
  - MaintenanceChronicle.Application.Contracts.Users.Commands.CheckUserLogInCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.CreateNewUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateAccessTokenFromClaimsCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateClaimsListForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmTokenCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmationEmailForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordCreateEmailForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetEmailForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetTokenCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.ManageRolesForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.ResetPasswordForUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.UpdateUserCommand
  - MaintenanceChronicle.Application.Contracts.Users.Commands.ValidateEmailConfirmationTokenCommand
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.Users.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.Users.Commands
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.CheckUserLogInCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.CheckUserLogInCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.CheckUserLogInCommand.html
  name: CheckUserLogInCommand
  nameWithType: CheckUserLogInCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.CheckUserLogInCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.CreateNewUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.CreateNewUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.CreateNewUserCommand.html
  name: CreateNewUserCommand
  nameWithType: CreateNewUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.CreateNewUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateAccessTokenFromClaimsCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateAccessTokenFromClaimsCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateAccessTokenFromClaimsCommand.html
  name: GenerateAccessTokenFromClaimsCommand
  nameWithType: GenerateAccessTokenFromClaimsCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateAccessTokenFromClaimsCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateClaimsListForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateClaimsListForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateClaimsListForUserCommand.html
  name: GenerateClaimsListForUserCommand
  nameWithType: GenerateClaimsListForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateClaimsListForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmationEmailForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmationEmailForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmationEmailForUserCommand.html
  name: GenerateEmailConfirmationEmailForUserCommand
  nameWithType: GenerateEmailConfirmationEmailForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmationEmailForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmTokenCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmTokenCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmTokenCommand.html
  name: GenerateEmailConfirmTokenCommand
  nameWithType: GenerateEmailConfirmTokenCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GenerateEmailConfirmTokenCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordCreateEmailForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordCreateEmailForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordCreateEmailForUserCommand.html
  name: GeneratePasswordCreateEmailForUserCommand
  nameWithType: GeneratePasswordCreateEmailForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordCreateEmailForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetEmailForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetEmailForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetEmailForUserCommand.html
  name: GeneratePasswordResetEmailForUserCommand
  nameWithType: GeneratePasswordResetEmailForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetEmailForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetTokenCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetTokenCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetTokenCommand.html
  name: GeneratePasswordResetTokenCommand
  nameWithType: GeneratePasswordResetTokenCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.GeneratePasswordResetTokenCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.ManageRolesForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.ManageRolesForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.ManageRolesForUserCommand.html
  name: ManageRolesForUserCommand
  nameWithType: ManageRolesForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.ManageRolesForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.ResetPasswordForUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.ResetPasswordForUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.ResetPasswordForUserCommand.html
  name: ResetPasswordForUserCommand
  nameWithType: ResetPasswordForUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.ResetPasswordForUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.UpdateUserCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.UpdateUserCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.UpdateUserCommand.html
  name: UpdateUserCommand
  nameWithType: UpdateUserCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.UpdateUserCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands.ValidateEmailConfirmationTokenCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Commands.ValidateEmailConfirmationTokenCommand
  parent: MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.Application.Contracts.Users.Commands.ValidateEmailConfirmationTokenCommand.html
  name: ValidateEmailConfirmationTokenCommand
  nameWithType: ValidateEmailConfirmationTokenCommand
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands.ValidateEmailConfirmationTokenCommand
- uid: MaintenanceChronicle.Application.Contracts.Users.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.Users.Commands
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Users.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.Users.Commands
  fullName: MaintenanceChronicle.Application.Contracts.Users.Commands
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users
    name: Users
    href: MaintenanceChronicle.Application.Contracts.Users.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Users.Commands.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users
    name: Users
    href: MaintenanceChronicle.Application.Contracts.Users.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Users.Commands.html
