### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  id: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMaintenanceReminderDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMrExtension
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMaintenanceReminderDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMaintenanceReminderDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMaintenanceReminderDto.html
  name: NewMaintenanceReminderDto
  nameWithType: NewMaintenanceReminderDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMaintenanceReminderDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMrExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMrExtension
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMrExtension.html
  name: NewMrExtension
  nameWithType: NewMrExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.NewMrExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.Dto.html
