### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.EmailMessages.Queries
  commentId: N:MaintenanceChronicle.Application.EmailMessages.Queries
  id: MaintenanceChronicle.Application.EmailMessages.Queries
  children:
  - MaintenanceChronicle.Application.EmailMessages.Queries.GetListOfEmailMessagesQueryHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.EmailMessages.Queries
  nameWithType: MaintenanceChronicle.Application.EmailMessages.Queries
  fullName: MaintenanceChronicle.Application.EmailMessages.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.EmailMessages.Queries.GetListOfEmailMessagesQueryHandler
  commentId: T:MaintenanceChronicle.Application.EmailMessages.Queries.GetListOfEmailMessagesQueryHandler
  href: MaintenanceChronicle.Application.EmailMessages.Queries.GetListOfEmailMessagesQueryHandler.html
  name: GetListOfEmailMessagesQueryHandler
  nameWithType: GetListOfEmailMessagesQueryHandler
  fullName: MaintenanceChronicle.Application.EmailMessages.Queries.GetListOfEmailMessagesQueryHandler
