### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  id: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommand
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommand
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommand
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommand
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommand.html
  name: CreateNewMaintenanceReminderCommand
  nameWithType: CreateNewMaintenanceReminderCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommand.html
  name: GenerateMaintenanceReminderEmailCommand
  nameWithType: GenerateMaintenanceReminderEmailCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommand.html
  name: MarkMaintenanceReminderAsSentCommand
  nameWithType: MarkMaintenanceReminderAsSentCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommand.html
  name: UpdateMaintenanceReminderCommand
  nameWithType: UpdateMaintenanceReminderCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Commands.html
