### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Queries
  commentId: N:MaintenanceChronicle.Application.MaintenanceReminders.Queries
  id: MaintenanceChronicle.Application.MaintenanceReminders.Queries
  children:
  - MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQueryHandler
  - MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQueryHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.MaintenanceReminders.Queries
  nameWithType: MaintenanceChronicle.Application.MaintenanceReminders.Queries
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQueryHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQueryHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQueryHandler.html
  name: GetAllDueMaintenanceRemindersQueryHandler
  nameWithType: GetAllDueMaintenanceRemindersQueryHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQueryHandler
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQueryHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQueryHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQueryHandler.html
  name: GetAllMaintenanceRemindersForMachineQueryHandler
  nameWithType: GetAllMaintenanceRemindersForMachineQueryHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQueryHandler
