### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  id: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.CreateNewMaintenanceRecordCommand
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.UpdateMaintenanceRecordCommand
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.CreateNewMaintenanceRecordCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.CreateNewMaintenanceRecordCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.CreateNewMaintenanceRecordCommand.html
  name: CreateNewMaintenanceRecordCommand
  nameWithType: CreateNewMaintenanceRecordCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.CreateNewMaintenanceRecordCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.UpdateMaintenanceRecordCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.UpdateMaintenanceRecordCommand
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.UpdateMaintenanceRecordCommand.html
  name: UpdateMaintenanceRecordCommand
  nameWithType: UpdateMaintenanceRecordCommand
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.UpdateMaintenanceRecordCommand
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Commands.html
