### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  id: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  children:
  - MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.GetStoredRefreshTokenQuery
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.GetStoredRefreshTokenQuery
  commentId: T:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.GetStoredRefreshTokenQuery
  parent: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.GetStoredRefreshTokenQuery.html
  name: GetStoredRefreshTokenQuery
  nameWithType: GetStoredRefreshTokenQuery
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.GetStoredRefreshTokenQuery
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens
    name: RefreshTokens
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens
    name: RefreshTokens
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.html
