### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.MaintenanceRecords.Queries
  commentId: N:MaintenanceChronicle.Application.MaintenanceRecords.Queries
  id: MaintenanceChronicle.Application.MaintenanceRecords.Queries
  children:
  - MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetListOfMaintenanceRecordsQueryHandler
  - MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordByIdQueryHandler
  - MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQueryHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.MaintenanceRecords.Queries
  nameWithType: MaintenanceChronicle.Application.MaintenanceRecords.Queries
  fullName: MaintenanceChronicle.Application.MaintenanceRecords.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetListOfMaintenanceRecordsQueryHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetListOfMaintenanceRecordsQueryHandler
  href: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetListOfMaintenanceRecordsQueryHandler.html
  name: GetListOfMaintenanceRecordsQueryHandler
  nameWithType: GetListOfMaintenanceRecordsQueryHandler
  fullName: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetListOfMaintenanceRecordsQueryHandler
- uid: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordByIdQueryHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordByIdQueryHandler
  href: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordByIdQueryHandler.html
  name: GetMaintenanceRecordByIdQueryHandler
  nameWithType: GetMaintenanceRecordByIdQueryHandler
  fullName: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordByIdQueryHandler
- uid: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQueryHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQueryHandler
  href: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQueryHandler.html
  name: GetMaintenanceRecordsByMachineIdQueryHandler
  nameWithType: GetMaintenanceRecordsByMachineIdQueryHandler
  fullName: MaintenanceChronicle.Application.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQueryHandler
