### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.RefreshTokens.Queries
  commentId: N:MaintenanceChronicle.Application.RefreshTokens.Queries
  id: MaintenanceChronicle.Application.RefreshTokens.Queries
  children:
  - MaintenanceChronicle.Application.RefreshTokens.Queries.GetStoredRefreshTokenQueryHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.RefreshTokens.Queries
  nameWithType: MaintenanceChronicle.Application.RefreshTokens.Queries
  fullName: MaintenanceChronicle.Application.RefreshTokens.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.RefreshTokens.Queries.GetStoredRefreshTokenQueryHandler
  commentId: T:MaintenanceChronicle.Application.RefreshTokens.Queries.GetStoredRefreshTokenQueryHandler
  href: MaintenanceChronicle.Application.RefreshTokens.Queries.GetStoredRefreshTokenQueryHandler.html
  name: GetStoredRefreshTokenQueryHandler
  nameWithType: GetStoredRefreshTokenQueryHandler
  fullName: MaintenanceChronicle.Application.RefreshTokens.Queries.GetStoredRefreshTokenQueryHandler
