### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  id: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailExtension
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListExtension
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineExtension
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailDto.html
  name: MaintenanceRecordDetailDto
  nameWithType: MaintenanceRecordDetailDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailExtension
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailExtension.html
  name: MaintenanceRecordDetailExtension
  nameWithType: MaintenanceRecordDetailExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordDetailExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListDto.html
  name: MaintenanceRecordInListDto
  nameWithType: MaintenanceRecordInListDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListExtension
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListExtension.html
  name: MaintenanceRecordInListExtension
  nameWithType: MaintenanceRecordInListExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineDto.html
  name: MaintenanceRecordInListForMachineDto
  nameWithType: MaintenanceRecordInListForMachineDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineExtension
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineExtension.html
  name: MaintenanceRecordInListForMachineExtension
  nameWithType: MaintenanceRecordInListForMachineExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.MaintenanceRecordInListForMachineExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.Dto.html
