### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  id: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQuery
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQuery
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQuery
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQuery.html
  name: GetMaintenanceRecordsByMachineIdQuery
  nameWithType: GetMaintenanceRecordsByMachineIdQuery
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.GetMaintenanceRecordsByMachineIdQuery
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords
    name: MaintenanceRecords
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceRecords.Queries.html
