### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  id: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDtoExtension
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDtoExtension
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDto
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDtoExtension
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDto.html
  name: DueMaintenanceReminderDto
  nameWithType: DueMaintenanceReminderDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDtoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDtoExtension
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDtoExtension.html
  name: DueMaintenanceReminderDtoExtension
  nameWithType: DueMaintenanceReminderDtoExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.DueMaintenanceReminderDtoExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDto.html
  name: MaintenanceReminderDetailDto
  nameWithType: MaintenanceReminderDetailDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDtoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDtoExtension
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDtoExtension.html
  name: MaintenanceReminderDetailDtoExtension
  nameWithType: MaintenanceReminderDetailDtoExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderDetailDtoExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDto
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDto
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDto.html
  name: MaintenanceReminderInListForMachineDto
  nameWithType: MaintenanceReminderInListForMachineDto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDto
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDtoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDtoExtension
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDtoExtension.html
  name: MaintenanceReminderInListForMachineDtoExtension
  nameWithType: MaintenanceReminderInListForMachineDtoExtension
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.MaintenanceReminderInListForMachineDtoExtension
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.Dto.html
