### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  id: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoDto
  - MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoExtension
  - MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserDetailDto
  - MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserListDto
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoDto
  parent: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoDto.html
  name: LoggedInUserInfoDto
  nameWithType: LoggedInUserInfoDto
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoDto
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoExtension
  href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoExtension.html
  name: LoggedInUserInfoExtension
  nameWithType: LoggedInUserInfoExtension
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.LoggedInUserInfoExtension
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserDetailDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserDetailDto
  href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserDetailDto.html
  name: UserDetailDto
  nameWithType: UserDetailDto
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserDetailDto
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserListDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserListDto
  href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserListDto.html
  name: UserListDto
  nameWithType: UserListDto
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.UserListDto
- uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users
    name: Users
    href: MaintenanceChronicle.Application.Contracts.Users.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Users.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users
    name: Users
    href: MaintenanceChronicle.Application.Contracts.Users.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Users.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Users.Queries.Dto.html
