### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Customers.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.Customers.Queries
  id: MaintenanceChronicle.Application.Contracts.Customers.Queries
  children:
  - MaintenanceChronicle.Application.Contracts.Customers.Queries.GetCustomerDetailForLocationQuery
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.Customers.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.Customers.Queries
  fullName: MaintenanceChronicle.Application.Contracts.Customers.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.Customers.Queries.GetCustomerDetailForLocationQuery
  commentId: T:MaintenanceChronicle.Application.Contracts.Customers.Queries.GetCustomerDetailForLocationQuery
  parent: MaintenanceChronicle.Application.Contracts.Customers.Queries
  href: MaintenanceChronicle.Application.Contracts.Customers.Queries.GetCustomerDetailForLocationQuery.html
  name: GetCustomerDetailForLocationQuery
  nameWithType: GetCustomerDetailForLocationQuery
  fullName: MaintenanceChronicle.Application.Contracts.Customers.Queries.GetCustomerDetailForLocationQuery
- uid: MaintenanceChronicle.Application.Contracts.Customers.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.Customers.Queries
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Customers.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.Customers.Queries
  fullName: MaintenanceChronicle.Application.Contracts.Customers.Queries
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Customers
    name: Customers
    href: MaintenanceChronicle.Application.Contracts.Customers.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Customers.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Customers.Queries.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Customers
    name: Customers
    href: MaintenanceChronicle.Application.Contracts.Customers.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Customers.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Customers.Queries.html
