### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.Tenants.Commands
  id: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  children:
  - MaintenanceChronicle.Application.Contracts.Tenants.Commands.AddTenantClaimsListCommand
  - MaintenanceChronicle.Application.Contracts.Tenants.Commands.UpdateTenantCommand
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  fullName: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands.AddTenantClaimsListCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Tenants.Commands.AddTenantClaimsListCommand
  parent: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  href: MaintenanceChronicle.Application.Contracts.Tenants.Commands.AddTenantClaimsListCommand.html
  name: AddTenantClaimsListCommand
  nameWithType: AddTenantClaimsListCommand
  fullName: MaintenanceChronicle.Application.Contracts.Tenants.Commands.AddTenantClaimsListCommand
- uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands.UpdateTenantCommand
  commentId: T:MaintenanceChronicle.Application.Contracts.Tenants.Commands.UpdateTenantCommand
  parent: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  href: MaintenanceChronicle.Application.Contracts.Tenants.Commands.UpdateTenantCommand.html
  name: UpdateTenantCommand
  nameWithType: UpdateTenantCommand
  fullName: MaintenanceChronicle.Application.Contracts.Tenants.Commands.UpdateTenantCommand
- uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  commentId: N:MaintenanceChronicle.Application.Contracts.Tenants.Commands
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  nameWithType: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  fullName: MaintenanceChronicle.Application.Contracts.Tenants.Commands
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Tenants
    name: Tenants
    href: MaintenanceChronicle.Application.Contracts.Tenants.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Tenants.Commands.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Tenants
    name: Tenants
    href: MaintenanceChronicle.Application.Contracts.Tenants.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Tenants.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Tenants.Commands.html
