### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Commands
  commentId: N:MaintenanceChronicle.Application.MaintenanceReminders.Commands
  id: MaintenanceChronicle.Application.MaintenanceReminders.Commands
  children:
  - MaintenanceChronicle.Application.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommandHandler
  - MaintenanceChronicle.Application.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommandHandler
  - MaintenanceChronicle.Application.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommandHandler
  - MaintenanceChronicle.Application.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommandHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.MaintenanceReminders.Commands
  nameWithType: MaintenanceChronicle.Application.MaintenanceReminders.Commands
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommandHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommandHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommandHandler.html
  name: CreateNewMaintenanceReminderCommandHandler
  nameWithType: CreateNewMaintenanceReminderCommandHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Commands.CreateNewMaintenanceReminderCommandHandler
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommandHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommandHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommandHandler.html
  name: GenerateMaintenanceReminderEmailCommandHandler
  nameWithType: GenerateMaintenanceReminderEmailCommandHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Commands.GenerateMaintenanceReminderEmailCommandHandler
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommandHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommandHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommandHandler.html
  name: MarkMaintenanceReminderAsSentCommandHandler
  nameWithType: MarkMaintenanceReminderAsSentCommandHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Commands.MarkMaintenanceReminderAsSentCommandHandler
- uid: MaintenanceChronicle.Application.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommandHandler
  commentId: T:MaintenanceChronicle.Application.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommandHandler
  href: MaintenanceChronicle.Application.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommandHandler.html
  name: UpdateMaintenanceReminderCommandHandler
  nameWithType: UpdateMaintenanceReminderCommandHandler
  fullName: MaintenanceChronicle.Application.MaintenanceReminders.Commands.UpdateMaintenanceReminderCommandHandler
