### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  id: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDto
  - MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDtoExtension
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDto
  commentId: T:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDto
  parent: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDto.html
  name: RefreshTokenDto
  nameWithType: RefreshTokenDto
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDto
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDtoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDtoExtension
  href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDtoExtension.html
  name: RefreshTokenDtoExtension
  nameWithType: RefreshTokenDtoExtension
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.RefreshTokenDtoExtension
- uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens
    name: RefreshTokens
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens
    name: RefreshTokens
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.RefreshTokens.Queries.Dto.html
