### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  id: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  children:
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQuery
  - MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQuery
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application.Contracts
references:
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQuery
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQuery
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQuery.html
  name: GetAllDueMaintenanceRemindersQuery
  nameWithType: GetAllDueMaintenanceRemindersQuery
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllDueMaintenanceRemindersQuery
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQuery
  commentId: T:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQuery
  parent: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQuery.html
  name: GetAllMaintenanceRemindersForMachineQuery
  nameWithType: GetAllMaintenanceRemindersForMachineQuery
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.GetAllMaintenanceRemindersForMachineQuery
- uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  fullName: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders
    name: MaintenanceReminders
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.MaintenanceReminders.Queries.html
