### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Users.Commands
  commentId: N:MaintenanceChronicle.Application.Users.Commands
  id: MaintenanceChronicle.Application.Users.Commands
  children:
  - MaintenanceChronicle.Application.Users.Commands.CheckUserLogInCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.CreateNewUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GenerateAccessTokenFromClaimsCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GenerateClaimsListForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmTokenCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmationEmailForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GeneratePasswordCreateEmailForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetEmailForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetTokenCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.ManageRolesForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.ResetPasswordForUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.UpdateUserCommandHandler
  - MaintenanceChronicle.Application.Users.Commands.ValidateEmailConfirmationTokenCommandHandler
  langs:
  - csharp
  - vb
  name: MaintenanceChronicle.Application.Users.Commands
  nameWithType: MaintenanceChronicle.Application.Users.Commands
  fullName: MaintenanceChronicle.Application.Users.Commands
  type: Namespace
  assemblies:
  - MaintenanceChronicle.Application
references:
- uid: MaintenanceChronicle.Application.Users.Commands.CheckUserLogInCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.CheckUserLogInCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.CheckUserLogInCommandHandler.html
  name: CheckUserLogInCommandHandler
  nameWithType: CheckUserLogInCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.CheckUserLogInCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.CreateNewUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.CreateNewUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.CreateNewUserCommandHandler.html
  name: CreateNewUserCommandHandler
  nameWithType: CreateNewUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.CreateNewUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GenerateAccessTokenFromClaimsCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GenerateAccessTokenFromClaimsCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GenerateAccessTokenFromClaimsCommandHandler.html
  name: GenerateAccessTokenFromClaimsCommandHandler
  nameWithType: GenerateAccessTokenFromClaimsCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GenerateAccessTokenFromClaimsCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GenerateClaimsListForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GenerateClaimsListForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GenerateClaimsListForUserCommandHandler.html
  name: GenerateClaimsListForUserCommandHandler
  nameWithType: GenerateClaimsListForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GenerateClaimsListForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmationEmailForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmationEmailForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmationEmailForUserCommandHandler.html
  name: GenerateEmailConfirmationEmailForUserCommandHandler
  nameWithType: GenerateEmailConfirmationEmailForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmationEmailForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmTokenCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmTokenCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmTokenCommandHandler.html
  name: GenerateEmailConfirmTokenCommandHandler
  nameWithType: GenerateEmailConfirmTokenCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GenerateEmailConfirmTokenCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordCreateEmailForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GeneratePasswordCreateEmailForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordCreateEmailForUserCommandHandler.html
  name: GeneratePasswordCreateEmailForUserCommandHandler
  nameWithType: GeneratePasswordCreateEmailForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordCreateEmailForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetEmailForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetEmailForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetEmailForUserCommandHandler.html
  name: GeneratePasswordResetEmailForUserCommandHandler
  nameWithType: GeneratePasswordResetEmailForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetEmailForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetTokenCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetTokenCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetTokenCommandHandler.html
  name: GeneratePasswordResetTokenCommandHandler
  nameWithType: GeneratePasswordResetTokenCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.GeneratePasswordResetTokenCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.ManageRolesForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.ManageRolesForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.ManageRolesForUserCommandHandler.html
  name: ManageRolesForUserCommandHandler
  nameWithType: ManageRolesForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.ManageRolesForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.ResetPasswordForUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.ResetPasswordForUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.ResetPasswordForUserCommandHandler.html
  name: ResetPasswordForUserCommandHandler
  nameWithType: ResetPasswordForUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.ResetPasswordForUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.UpdateUserCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.UpdateUserCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.UpdateUserCommandHandler.html
  name: UpdateUserCommandHandler
  nameWithType: UpdateUserCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.UpdateUserCommandHandler
- uid: MaintenanceChronicle.Application.Users.Commands.ValidateEmailConfirmationTokenCommandHandler
  commentId: T:MaintenanceChronicle.Application.Users.Commands.ValidateEmailConfirmationTokenCommandHandler
  href: MaintenanceChronicle.Application.Users.Commands.ValidateEmailConfirmationTokenCommandHandler.html
  name: ValidateEmailConfirmationTokenCommandHandler
  nameWithType: ValidateEmailConfirmationTokenCommandHandler
  fullName: MaintenanceChronicle.Application.Users.Commands.ValidateEmailConfirmationTokenCommandHandler
