### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1
  commentId: T:MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1
  id: GetListOfEntityQuery`1
  parent: MaintenanceChronicle.Application.Contracts.Utils.Queries
  children:
  - MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor
  langs:
  - csharp
  - vb
  name: GetListOfEntityQuery<TEntity>
  nameWithType: GetListOfEntityQuery<TEntity>
  fullName: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery<TEntity>
  type: Class
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Utils/Queries/GetListOfEntityQuery.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: GetListOfEntityQuery
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Utils/Queries/GetListOfEntityQuery.cs
    startLine: 4
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Utils.Queries
  syntax:
    content: 'public record GetListOfEntityQuery<TEntity> : IRequest<List<TEntity>>, IBaseRequest, IEquatable<GetListOfEntityQuery<TEntity>>'
    typeParameters:
    - id: TEntity
    content.vb: Public Class GetListOfEntityQuery(Of TEntity) Implements IRequest(Of List(Of TEntity)), IBaseRequest, IEquatable(Of GetListOfEntityQuery(Of TEntity))
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{System.Collections.Generic.List{{TEntity}}}
  - MediatR.IBaseRequest
  - System.IEquatable{MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: GetListOfEntityQuery(Of TEntity)
  fullName.vb: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery(Of TEntity)
  name.vb: GetListOfEntityQuery(Of TEntity)
- uid: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor
  commentId: M:MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor
  id: '#ctor'
  parent: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1
  langs:
  - csharp
  - vb
  name: GetListOfEntityQuery()
  nameWithType: GetListOfEntityQuery<TEntity>.GetListOfEntityQuery()
  fullName: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery<TEntity>.GetListOfEntityQuery()
  type: Constructor
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Utils/Queries/GetListOfEntityQuery.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: .ctor
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Utils/Queries/GetListOfEntityQuery.cs
    startLine: 4
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Utils.Queries
  syntax:
    content: public GetListOfEntityQuery()
    content.vb: Public Sub New()
  overload: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor*
  nameWithType.vb: GetListOfEntityQuery(Of TEntity).New()
  fullName.vb: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery(Of TEntity).New()
  name.vb: New()
references:
- uid: MaintenanceChronicle.Application.Contracts.Utils.Queries
  commentId: N:MaintenanceChronicle.Application.Contracts.Utils.Queries
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Utils.Queries
  nameWithType: MaintenanceChronicle.Application.Contracts.Utils.Queries
  fullName: MaintenanceChronicle.Application.Contracts.Utils.Queries
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Utils
    name: Utils
    href: MaintenanceChronicle.Application.Contracts.Utils.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Utils.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Utils.Queries.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Utils
    name: Utils
    href: MaintenanceChronicle.Application.Contracts.Utils.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Utils.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Utils.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{System.Collections.Generic.List{{TEntity}}}
  commentId: T:MediatR.IRequest{System.Collections.Generic.List{`0}}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: IRequest<List<TEntity>>
  nameWithType: IRequest<List<TEntity>>
  fullName: MediatR.IRequest<System.Collections.Generic.List<TEntity>>
  nameWithType.vb: IRequest(Of List(Of TEntity))
  fullName.vb: MediatR.IRequest(Of System.Collections.Generic.List(Of TEntity))
  name.vb: IRequest(Of List(Of TEntity))
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: TEntity
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.IEquatable{MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1}
  commentId: T:System.IEquatable{MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<GetListOfEntityQuery<TEntity>>
  nameWithType: IEquatable<GetListOfEntityQuery<TEntity>>
  fullName: System.IEquatable<MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery<TEntity>>
  nameWithType.vb: IEquatable(Of GetListOfEntityQuery(Of TEntity))
  fullName.vb: System.IEquatable(Of MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery(Of TEntity))
  name.vb: IEquatable(Of GetListOfEntityQuery(Of TEntity))
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1
    name: GetListOfEntityQuery
    href: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery-1.html
  - name: <
  - name: TEntity
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1
    name: GetListOfEntityQuery
    href: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery`1.#ctor
  href: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery-1.html#MaintenanceChronicle_Application_Contracts_Utils_Queries_GetListOfEntityQuery_1__ctor
  name: GetListOfEntityQuery
  nameWithType: GetListOfEntityQuery<TEntity>.GetListOfEntityQuery
  fullName: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery<TEntity>.GetListOfEntityQuery
  nameWithType.vb: GetListOfEntityQuery(Of TEntity).New
  fullName.vb: MaintenanceChronicle.Application.Contracts.Utils.Queries.GetListOfEntityQuery(Of TEntity).New
  name.vb: New
