### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto
  id: ContactsInLocationDto
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
  - MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
  langs:
  - csharp
  - vb
  name: ContactsInLocationDto
  nameWithType: ContactsInLocationDto
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto
  type: Class
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: ContactsInLocationDto
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
    startLine: 2
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  syntax:
    content: public class ContactsInLocationDto
    content.vb: Public Class ContactsInLocationDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
  commentId: P:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
  id: LocationId
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto
  langs:
  - csharp
  - vb
  name: LocationId
  nameWithType: ContactsInLocationDto.LocationId
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
  type: Property
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: LocationId
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
    startLine: 4
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  syntax:
    content: public Guid LocationId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property LocationId As Guid
  overload: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId*
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
  commentId: P:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
  id: ContactIds
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto
  langs:
  - csharp
  - vb
  name: ContactIds
  nameWithType: ContactsInLocationDto.ContactIds
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
  type: Property
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: ContactIds
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/ContactsInLocationDto.cs
    startLine: 5
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  syntax:
    content: public required Guid[] ContactIds { get; set; }
    parameters: []
    return:
      type: System.Guid[]
    content.vb: Public Property ContactIds As Guid()
  overload: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds*
references:
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations
    name: Locations
    href: MaintenanceChronicle.Application.Contracts.Locations.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations
    name: Locations
    href: MaintenanceChronicle.Application.Contracts.Locations.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
  href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.html#MaintenanceChronicle_Application_Contracts_Locations_Commands_Dto_ContactsInLocationDto_LocationId
  name: LocationId
  nameWithType: ContactsInLocationDto.LocationId
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.LocationId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
  href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.html#MaintenanceChronicle_Application_Contracts_Locations_Commands_Dto_ContactsInLocationDto_ContactIds
  name: ContactIds
  nameWithType: ContactsInLocationDto.ContactIds
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.ContactsInLocationDto.ContactIds
- uid: System.Guid[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid[]
  nameWithType: Guid[]
  fullName: System.Guid[]
  nameWithType.vb: Guid()
  fullName.vb: System.Guid()
  name.vb: Guid()
  spec.csharp:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: (
  - name: )
