### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  id: MachineInListForLocationDto
  parent: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
  - MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
  - MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
  langs:
  - csharp
  - vb
  name: MachineInListForLocationDto
  nameWithType: MachineInListForLocationDto
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  type: Class
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: MachineInListForLocationDto
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
    startLine: 4
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  syntax:
    content: public class MachineInListForLocationDto
    content.vb: Public Class MachineInListForLocationDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
  commentId: P:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
  id: Id
  parent: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: MachineInListForLocationDto.Id
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
  type: Property
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: Id
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
    startLine: 6
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id*
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
  commentId: P:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
  id: Model
  parent: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  langs:
  - csharp
  - vb
  name: Model
  nameWithType: MachineInListForLocationDto.Model
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
  type: Property
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: Model
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
    startLine: 7
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  syntax:
    content: public required string Model { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Model As String
  overload: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model*
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
  commentId: P:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
  id: SerialNumber
  parent: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto
  langs:
  - csharp
  - vb
  name: SerialNumber
  nameWithType: MachineInListForLocationDto.SerialNumber
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
  type: Property
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: SerialNumber
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Machines/Queries/Dto/MachineInListForLocationDto.cs
    startLine: 8
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  syntax:
    content: public required string SerialNumber { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SerialNumber As String
  overload: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber*
references:
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines
    name: Machines
    href: MaintenanceChronicle.Application.Contracts.Machines.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Machines.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines
    name: Machines
    href: MaintenanceChronicle.Application.Contracts.Machines.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines.Queries
    name: Queries
    href: MaintenanceChronicle.Application.Contracts.Machines.Queries.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
  href: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.html#MaintenanceChronicle_Application_Contracts_Machines_Queries_Dto_MachineInListForLocationDto_Id
  name: Id
  nameWithType: MachineInListForLocationDto.Id
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
  href: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.html#MaintenanceChronicle_Application_Contracts_Machines_Queries_Dto_MachineInListForLocationDto_Model
  name: Model
  nameWithType: MachineInListForLocationDto.Model
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.Model
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
  href: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.html#MaintenanceChronicle_Application_Contracts_Machines_Queries_Dto_MachineInListForLocationDto_SerialNumber
  name: SerialNumber
  nameWithType: MachineInListForLocationDto.SerialNumber
  fullName: MaintenanceChronicle.Application.Contracts.Machines.Queries.Dto.MachineInListForLocationDto.SerialNumber
