### YamlMime:ManagedReference
items:
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension
  commentId: T:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension
  id: NewLocationDtoExtension
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  children:
  - MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity(MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto)
  langs:
  - csharp
  - vb
  name: NewLocationDtoExtension
  nameWithType: NewLocationDtoExtension
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension
  type: Class
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/NewLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: NewLocationDtoExtension
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/NewLocationDto.cs
    startLine: 12
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  syntax:
    content: public static class NewLocationDtoExtension
    content.vb: Public Module NewLocationDtoExtension
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity(MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto)
  commentId: M:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity(MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto)
  id: ToEntity(MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto)
  isExtensionMethod: true
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension
  langs:
  - csharp
  - vb
  name: ToEntity(NewLocationDto)
  nameWithType: NewLocationDtoExtension.ToEntity(NewLocationDto)
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity(MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto)
  type: Method
  source:
    remote:
      path: src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/NewLocationDto.cs
      branch: dev
      repo: https://github.com/NicoSoftEngineer/ServiceTrackApi.git
    id: ToEntity
    path: ../MaintenanceChronicleApi/src/MaintenanceChronicle.Application.Contracts/Locations/Commands/Dto/NewLocationDto.cs
    startLine: 15
  assemblies:
  - MaintenanceChronicle.Application.Contracts
  namespace: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  syntax:
    content: public static Location ToEntity(this NewLocationDto newLocationDto)
    parameters:
    - id: newLocationDto
      type: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto
    return:
      type: MaintenanceChronicle.Data.Entities.Business.Location
    content.vb: Public Shared Function ToEntity(newLocationDto As NewLocationDto) As Location
  overload: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity*
references:
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  commentId: N:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  nameWithType: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations
    name: Locations
    href: MaintenanceChronicle.Application.Contracts.Locations.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Application
    name: Application
    href: MaintenanceChronicle.Application.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts
    name: Contracts
    href: MaintenanceChronicle.Application.Contracts.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations
    name: Locations
    href: MaintenanceChronicle.Application.Contracts.Locations.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands
    name: Commands
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.html
  - name: .
  - uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
    name: Dto
    href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity*
  commentId: Overload:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity
  href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.html#MaintenanceChronicle_Application_Contracts_Locations_Commands_Dto_NewLocationDtoExtension_ToEntity_MaintenanceChronicle_Application_Contracts_Locations_Commands_Dto_NewLocationDto_
  name: ToEntity
  nameWithType: NewLocationDtoExtension.ToEntity
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDtoExtension.ToEntity
- uid: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto
  commentId: T:MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto
  parent: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto
  href: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto.html
  name: NewLocationDto
  nameWithType: NewLocationDto
  fullName: MaintenanceChronicle.Application.Contracts.Locations.Commands.Dto.NewLocationDto
- uid: MaintenanceChronicle.Data.Entities.Business.Location
  commentId: T:MaintenanceChronicle.Data.Entities.Business.Location
  parent: MaintenanceChronicle.Data.Entities.Business
  href: MaintenanceChronicle.Data.Entities.Business.Location.html
  name: Location
  nameWithType: Location
  fullName: MaintenanceChronicle.Data.Entities.Business.Location
- uid: MaintenanceChronicle.Data.Entities.Business
  commentId: N:MaintenanceChronicle.Data.Entities.Business
  href: MaintenanceChronicle.html
  name: MaintenanceChronicle.Data.Entities.Business
  nameWithType: MaintenanceChronicle.Data.Entities.Business
  fullName: MaintenanceChronicle.Data.Entities.Business
  spec.csharp:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Data
    name: Data
    href: MaintenanceChronicle.Data.html
  - name: .
  - uid: MaintenanceChronicle.Data.Entities
    name: Entities
    href: MaintenanceChronicle.Data.Entities.html
  - name: .
  - uid: MaintenanceChronicle.Data.Entities.Business
    name: Business
    href: MaintenanceChronicle.Data.Entities.Business.html
  spec.vb:
  - uid: MaintenanceChronicle
    name: MaintenanceChronicle
    href: MaintenanceChronicle.html
  - name: .
  - uid: MaintenanceChronicle.Data
    name: Data
    href: MaintenanceChronicle.Data.html
  - name: .
  - uid: MaintenanceChronicle.Data.Entities
    name: Entities
    href: MaintenanceChronicle.Data.Entities.html
  - name: .
  - uid: MaintenanceChronicle.Data.Entities.Business
    name: Business
    href: MaintenanceChronicle.Data.Entities.Business.html
