name: Build and Deploy to Azure VM

on:
  push:
    branches: [feature/prodPipeline]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

    - name: Build Docker Image
      run: |
        IMAGE_NAME=ghcr.io/nicosoftengineer/machapi:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
          docker pull ghcr.io/nicosoftengineer/machapi
          docker stop machapi || true
          docker rm machapi || true
          docker run -d --name machapi -p 80:80 machapi
